language: php

php:
  - 5.6
 

before_install:
  - composer config github-oauth.github.com ${GH_TOKEN}

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
